apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greenhome-ingress
spec:
  rules:
  - host: greenhome.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greenhome-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: greenhome-backend
            port:
              number: 3000