apiVersion: v1
kind: Service
metadata:
  name: greenhome-backend
spec:
  selector:
    app: greenhome-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: greenhome-frontend
spec:
  selector:
    app: greenhome-frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP